version: '2'
services:
  db:
    restart: on-failure
    build:
      dockerfile: "./Docker/dockerfile.pg"
      context: "."
    container_name: db
    environment:
      - DEBUG=false
      - DB_USER=dot11admin
      - DB_PASS=dot11password
      - DB_NAME=dot11monitor
    volumes:
      - /srv/docker/postgresql:/var/lib/postgresql

  api:
    depends_on:
      - db
    container_name: api
    restart: on-failure
    build:
      dockerfile: "./Docker/dockerfile.api"
      context: "."
    ports:
      - "80:5000"
    environment:
      - DATABASE_URI=postgresql://dot11admin:dot11password@db/dot11monitor
      # user to execute sql, db MUST be configured to avoid risks from it's actions
      # comment this line to disable sql execution from user space
      - LIMITED_DATABASE_URI=postgresql://dot11viewer:dot11password@db/dot11monitor
      # default password for admin user if not exists
      - ADMIN_PASSWORD=admin
      - DISABLE_CSRF=true

  test:
    depends_on:
      - test_db
    container_name: test
    # restart: on-failure
    build:
      dockerfile: "./Docker/dockerfile.test"
      context: "."
    ports:
      - "80:5000"
    environment:
      - DATABASE_URI=postgresql://dot11admin:dot11password@test_db/dot11monitor
      - LIMITED_DATABASE_URI=postgresql://dot11viewer:dot11password@test_db/dot11monitor

  test_db:
    restart: on-failure
    build:
      dockerfile: "./Docker/dockerfile.pg"
      context: "."
    container_name: test_db
    environment:
      - DEBUG=false
      - DB_USER=dot11admin
      - DB_PASS=dot11password
      - DB_NAME=dot11monitor
    # volumes:
    #   - /srv/docker/postgresql:/var/lib/postgresql
